import { readFile, mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const workerRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = path.resolve(workerRoot, "..");
const episodesPath = path.join(repositoryRoot, "mssp_app", "public", "data", "episodes.json");
const modulePath = path.join(workerRoot, "src", "generated", "episodeCatalog.js");
const seedPath = path.join(workerRoot, "seed", "episode-catalog.sql");
const checkOnly = process.argv.includes("--check");

const payload = JSON.parse(await readFile(episodesPath, "utf8"));
const episodes = Array.isArray(payload) ? payload : payload.episodes;

if (!Array.isArray(episodes)) throw new Error("episodes.json does not contain an episodes array");

const episodeKeys = episodes.map((episode, index) => {
  if (typeof episode?.episodeKey !== "string" || !episode.episodeKey) {
    throw new Error(`Episode at index ${index} has no episodeKey`);
  }
  if (episode.episodeKey.length > 160) {
    throw new Error(`Episode key at index ${index} exceeds 160 characters`);
  }
  return episode.episodeKey;
});

if (new Set(episodeKeys).size !== episodeKeys.length) {
  throw new Error("episodes.json contains duplicate episodeKey values");
}

const moduleSource = [
  "// Generated by scripts/generateCatalog.mjs. Do not edit by hand.",
  `export const EPISODE_KEYS = new Set(${JSON.stringify(episodeKeys, null, 2)});`,
  "",
].join("\n");

const sqlValues = episodeKeys
  .map((episodeKey) => `  ('${episodeKey.replaceAll("'", "''")}')`)
  .join(",\n");
const seedSource = [
  "-- Generated by scripts/generateCatalog.mjs. Do not edit by hand.",
  "INSERT OR IGNORE INTO episode_catalog (episode_key) VALUES",
  `${sqlValues};`,
  "",
].join("\n");

if (checkOnly) {
  const [currentModule, currentSeed] = await Promise.all([
    readFile(modulePath, "utf8"),
    readFile(seedPath, "utf8"),
  ]);
  if (currentModule !== moduleSource || currentSeed !== seedSource) {
    throw new Error("Generated catalog artifacts are stale; run npm run catalog:generate");
  }
  console.log(`Catalog artifacts are current (${episodeKeys.length} episode keys).`);
} else {
  await Promise.all([
    mkdir(path.dirname(modulePath), { recursive: true }),
    mkdir(path.dirname(seedPath), { recursive: true }),
  ]);
  await Promise.all([
    writeFile(modulePath, moduleSource),
    writeFile(seedPath, seedSource),
  ]);
  console.log(`Generated catalog artifacts for ${episodeKeys.length} episode keys.`);
}
