// Converts data/baked-promo-cuts.json (measured by the offline alignment batch)
// into the module the worker bundles. Same pattern as mssp_signals_worker's
// generateCatalog.mjs. Run with --check in CI to catch stale artifacts.
import { readFile, mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const workerRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dataPath = path.join(workerRoot, "data", "baked-promo-cuts.json");
const modulePath = path.join(workerRoot, "src", "generated", "bakedPromoCuts.js");
const checkOnly = process.argv.includes("--check");

const payload = JSON.parse(await readFile(dataPath, "utf8"));
const entries = payload.entries;
if (!entries || typeof entries !== "object") throw new Error("baked-promo-cuts.json has no entries object");

const map = {};
for (const [id, entry] of Object.entries(entries)) {
  if (!/^GLT[A-Za-z0-9]+$/.test(id)) throw new Error(`bad megaphone id: ${id}`);
  if (!Number.isInteger(entry.postDaiBytes) || entry.postDaiBytes <= 0) throw new Error(`${id}: bad postDaiBytes`);
  if (entry.updated !== null && !/^\d+$/.test(String(entry.updated))) throw new Error(`${id}: bad updated`);
  if (!Array.isArray(entry.cuts) || !entry.cuts.length) throw new Error(`${id}: no cuts`);
  let previousEnd = -1;
  for (const cut of entry.cuts) {
    if (!Array.isArray(cut) || cut.length !== 2) throw new Error(`${id}: bad cut shape`);
    const [start, end] = cut;
    if (!Number.isInteger(start) || !Number.isInteger(end) || start < 0 || end <= start || end > entry.postDaiBytes) {
      throw new Error(`${id}: bad cut range ${start}-${end}`);
    }
    if (start < previousEnd) throw new Error(`${id}: overlapping cuts`);
    previousEnd = end;
  }
  map[id] = { updated: entry.updated, postDaiBytes: entry.postDaiBytes, cuts: entry.cuts };
}

const moduleSource = [
  "// Generated by scripts/generateBakedCuts.mjs. Do not edit by hand.",
  "// Byte ranges of promos baked into the episode masters (not declared as DAI",
  "// slots), measured by aligning the proxy's output against the promo-free",
  "// archive rips. Coordinates are in the POST-DAI file; each entry is guarded by",
  "// the exact post-DAI byte length so a re-uploaded or re-stitched master fails",
  "// open to unmodified audio.",
  `export const BAKED_PROMO_CUTS = ${JSON.stringify(map, null, 2)};`,
  "",
].join("\n");

if (checkOnly) {
  const current = await readFile(modulePath, "utf8");
  if (current !== moduleSource) throw new Error("bakedPromoCuts.js is stale; run npm run cuts:generate");
  console.log(`Baked cuts module is current (${Object.keys(map).length} episodes).`);
} else {
  await mkdir(path.dirname(modulePath), { recursive: true });
  await writeFile(modulePath, moduleSource);
  console.log(`Generated baked cuts module for ${Object.keys(map).length} episodes.`);
}
